# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2025, Felix Fontein

[collection_sources]
"amazon.aws" = "git+https://github.com/ansible-collections/amazon.aws.git,main"
"community.aws" = "git+https://github.com/ansible-collections/community.aws.git,main"
"community.crypto" = "git+https://github.com/ansible-collections/community.crypto.git,main"
"community.dns" = "git+https://github.com/ansible-collections/community.dns.git,main"
"community.general" = "git+https://github.com/ansible-collections/community.general.git,main"
"community.sops" = "git+https://github.com/ansible-collections/community.sops.git,main"
"community.internal_test_tools" = "git+https://github.com/ansible-collections/community.internal_test_tools.git,main"
"community.library_inventory_filtering" = "git+https://github.com/ansible-collections/community.library_inventory_filtering.git,stable-1"

[collection_sources_per_ansible.'2.11']
"community.crypto" = "git+https://github.com/ansible-collections/community.crypto.git,stable-2"
"community.sops" = "git+https://github.com/ansible-collections/community.sops.git,stable-1"

[collection_sources_per_ansible.'2.12']
"community.crypto" = "git+https://github.com/ansible-collections/community.crypto.git,stable-2"
"community.sops" = "git+https://github.com/ansible-collections/community.sops.git,stable-1"

[collection_sources_per_ansible.'2.13']
"community.crypto" = "git+https://github.com/ansible-collections/community.crypto.git,stable-2"
"community.sops" = "git+https://github.com/ansible-collections/community.sops.git,stable-1"

[collection_sources_per_ansible.'2.14']
"community.crypto" = "git+https://github.com/ansible-collections/community.crypto.git,stable-2"
"community.sops" = "git+https://github.com/ansible-collections/community.sops.git,stable-1"

[collection_sources_per_ansible.'2.15']
"community.crypto" = "git+https://github.com/ansible-collections/community.crypto.git,stable-2"

[collection_sources_per_ansible.'2.16']
"community.crypto" = "git+https://github.com/ansible-collections/community.crypto.git,stable-2"

[sessions]

[sessions.lint]
run_isort = false
run_black = false
run_flake8 = false
run_pylint = false
yamllint_config = ".yamllint"
run_mypy = false

[sessions.docs_check]
validate_collection_refs="all"

[sessions.license_check]

[sessions.extra_checks]
run_no_unwanted_files = true
no_unwanted_files_module_extensions = [".py"]
no_unwanted_files_yaml_extensions = [".yml"]

[sessions.build_import_check]
run_galaxy_importer = true

[sessions.ansible_test_sanity]
include_devel = true

[sessions.ansible_test_integration_w_default_container]
include_devel = true

[sessions.ansible_test_integration_w_default_container.ansible_vars_from_env_vars]
"github_token" = "GITHUB_TOKEN"

[sessions.ansible_test_integration_w_default_container.core_python_versions]
"2.11" = ["3.5", "3.6"]
"2.12" = ["2.6", "3.7"]
"2.13" = ["3.10"]
"2.14" = ["3.9"]
"2.15" = ["3.5"]
"2.16" = ["2.7", "3.6"]
"2.17" = ["3.7"]
"2.18" = ["3.8"]

[sessions.ansible_lint]
