---
namespace: felixfontein
name: acme
version: 0.2.0
readme: README.md
authors:
  - Felix Fontein (https://github.com/felixfontein)
description: Roles for ACME
license_file: COPYING
tags:
  - acme
  - letsencrypt
  - buypass
  - ssl
  - tls
  - https
  - encryption
  - security
  - web
  - sops
dependencies:
  community.crypto: '>=1.3.0'
  community.aws: '>=1.0.0'
  community.sops: '>=1.0.0'
  felixfontein.hosttech_dns: '>=1.1.0'
  felixfontein.tools: '>=1.1.0'
repository: https://github.com/felixfontein/ansible-acme
documentation: https://github.com/felixfontein/ansible-acme/tree/main/README.md#included-content
homepage: https://github.com/felixfontein/ansible-acme
issues: https://github.com/felixfontein/ansible-acme/issues
build_ignore:
  - .gitignore
  - felixfontein-acme-*.tar.gz
  - changelogs/.plugin-cache.yaml
  - tests/output
  - .cache
