---
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020, Felix Fontein

- name: "Revoke old certificates"
  community.crypto.acme_certificate_revoke:
    acme_directory: "{{ acme_certificate_acme_directory }}"
    acme_version: "{{ acme_certificate_acme_version }}"
    account_key: "{{ (acme_certificate_acme_account | default(omit)) if acme_certificate_revoke_with_acme_account else omit }}"
    account_key_content: >-
      {{ (acme_certificate_acme_account_content | default(omit)) if acme_certificate_revoke_with_acme_account else omit }}
    account_uri: "{{ (acme_certificate_acme_account_uri | default(omit)) if acme_certificate_revoke_with_acme_account else omit }}"
    revoke_reason: "{{ acme_certificate_revoke_reason }}"
    certificate: "{{ item[:-4] }}.pem"
    private_key_src: "{{ omit if acme_certificate_revoke_with_acme_account else (item[:-4] ~ '.key') }}"
    validate_certs: "{{ acme_certificate_validate_certs }}"
  delegate_to: localhost
  run_once: true
  with_fileglob:
    - "{{ acme_certificate_keys_old_path }}/*.key"

- name: "Revoke old certificates (sops encrypted keys)"
  community.crypto.acme_certificate_revoke:
    acme_directory: "{{ acme_certificate_acme_directory }}"
    acme_version: "{{ acme_certificate_acme_version }}"
    account_key: "{{ (acme_certificate_acme_account | default(omit)) if acme_certificate_revoke_with_acme_account else omit }}"
    account_key_content: >-
      {{ (acme_certificate_acme_account_content | default(omit)) if acme_certificate_revoke_with_acme_account else omit }}
    account_uri: "{{ (acme_certificate_acme_account_uri | default(omit)) if acme_certificate_revoke_with_acme_account else omit }}"
    revoke_reason: "{{ acme_certificate_revoke_reason }}"
    certificate: "{{ item[:-9] }}.pem"
    private_key_content: "{{ omit if acme_certificate_revoke_with_acme_account else lookup('community.sops.sops', item) }}"
    validate_certs: "{{ acme_certificate_validate_certs }}"
  delegate_to: localhost
  run_once: true
  with_fileglob:
    - "{{ acme_certificate_keys_old_path }}/*.key.sops"
