---
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020, Felix Fontein

# Create DNS challenges for DNS provider HostTech
- name: Creating challenge DNS entries for {{ ', '.join(acme_certificate_domains + acme_certificate_ips) }} via HostTech API
  community.dns.hosttech_dns_record_set:
    state: present
    zone_name: >-
      {{ item.key | felixfontein.acme._substitute_dns(acme_certificate_dns_substitution) | community.dns.get_registrable_domain }}
    record: "{{ item.key | felixfontein.acme._substitute_dns(acme_certificate_dns_substitution) }}"
    type: TXT
    ttl: "{{ 600 if acme_certificate_hosttech_token is defined else 300 }}"
    value: "{{ item.value }}"
    hosttech_username: "{{ acme_certificate_hosttech_username | default(omit) }}"
    hosttech_password: "{{ acme_certificate_hosttech_password | default(omit) }}"
    hosttech_token: "{{ acme_certificate_hosttech_token | default(omit) }}"
  delegate_to: localhost
  run_once: true
  with_dict: "{{ acme_certificate_INTERNAL_challenge.challenge_data_dns }}"

- name: Wait for DNS entries to propagate
  community.dns.wait_for_txt:
    records: >-
      {{ acme_certificate_INTERNAL_challenge.challenge_data_dns | dict2items(key_name='name', value_name='values') | list }}
    timeout: 120
  delegate_to: localhost
  run_once: true
