---
# Create DNS challenges for DNS provider HostTech
- name: Creating challenge DNS entries for {{ ', '.join(acme_certificate_domains + acme_certificate_ips) }} via HostTech API
  felixfontein.hosttech_dns.hosttech_dns_record:
    state: present
    zone: "{{ item.key | felixfontein.tools.dns_zone }}"
    record: "{{ item.key }}"
    type: TXT
    ttl: 300
    value: "{{ item.value }}"
    overwrite: true
    hosttech_username: "{{ acme_certificate_hosttech_username }}"
    hosttech_password: "{{ acme_certificate_hosttech_password }}"
  delegate_to: localhost
  run_once: true
  with_dict: "{{ acme_certificate_INTERNAL_challenge.challenge_data_dns }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs

- name: Wait for DNS entries to propagate
  felixfontein.tools.wait_for_txt:
    records: >-
      {{
        acme_certificate_INTERNAL_challenge.challenge_data_dns.items()
          | map('felixfontein.tools.list_to_dict', ['name', 'values'])
          | list
      }}
    timeout: 120
  delegate_to: localhost
  run_once: true
