---
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020, Felix Fontein

# Create DNS challenges for DNS provider Amazon Route53
- name: Creating challenge DNS entries for {{ ', '.join(acme_certificate_domains + acme_certificate_ips) }} via Route53
  amazon.aws.route53:
    state: present
    zone: "{{ item.key | felixfontein.acme._substitute_dns(acme_certificate_dns_substitution) | community.dns.get_registrable_domain }}"
    record: "{{ item.key | felixfontein.acme._substitute_dns(acme_certificate_dns_substitution) }}"
    type: TXT
    ttl: 60
    value: "{{ item.value | map('regex_replace', '^(.*)$', '\"\\1\"') | list }}"
    overwrite: true
    aws_access_key: "{{ acme_certificate_aws_access_key | default(omit) }}"
    aws_secret_key: "{{ acme_certificate_aws_secret_key | default(omit) }}"
    wait: false
  delegate_to: localhost
  run_once: true
  with_dict: "{{ acme_certificate_INTERNAL_challenge.challenge_data_dns }}"

- name: Wait for DNS entries to propagate
  community.dns.wait_for_txt:
    records: >-
      {{ acme_certificate_INTERNAL_challenge.challenge_data_dns | dict2items(key_name='name', value_name='values') | list }}
    timeout: 120
  delegate_to: localhost
  run_once: true
