---
# Create DNS challenges for DNS provider Amazon Route53
- name: Creating challenge DNS entries for {{ ', '.join(acme_certificate_domains + acme_certificate_ips) }} via Route53
  community.aws.route53:
    state: present
    zone: "{{ item.key | community.dns.get_registrable_domain }}"
    record: "{{ item.key }}"
    type: TXT
    ttl: 60
    value: "{{ item.value | map('regex_replace', '^(.*)$', '\"\\1\"' ) | list }}"
    overwrite: true
    aws_access_key: "{{ acme_certificate_aws_access_key }}"
    aws_secret_key: "{{ acme_certificate_aws_secret_key }}"
    wait: false
  delegate_to: localhost
  run_once: true
  with_dict: "{{ acme_certificate_INTERNAL_challenge.challenge_data_dns }}"

- name: Wait for DNS entries to propagate
  community.dns.wait_for_txt:
    records: >-
      {{ acme_certificate_INTERNAL_challenge.challenge_data_dns | dict2items(key_name='name', value_name='values') | list }}
    timeout: 120
  delegate_to: localhost
  run_once: true
