---
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2025, Felix Fontein

# Clean up DNS challenges for DNS provider Hetzner
- name: Cleaning up challenge DNS entries for {{ ', '.join(acme_certificate_domains + acme_certificate_ips) }} via Hetzner API
  community.dns.hetzner_dns_record_set:
    state: absent
    zone_name: >-
      {{ item.key | felixfontein.acme._substitute_dns(acme_certificate_dns_substitution) | community.dns.get_registrable_domain }}
    record: "{{ item.key | felixfontein.acme._substitute_dns(acme_certificate_dns_substitution) }}"
    type: TXT
    ttl: "60"
    value: "{{ item.value }}"
    hetzner_token: "{{ acme_certificate_hetzner_token | default(omit) }}"
  delegate_to: localhost
  run_once: true
  with_dict: "{{ acme_certificate_INTERNAL_challenge.challenge_data_dns | default({}) }}"
