---
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2023, Lucca Jiménez Könings

- name: DNS sanity checks (1/2)
  ansible.builtin.assert:
    that:
      - acme_certificate_cloudflare_token is defined
    msg: acme_certificate_cloudflare_token must be specified for Cloudflare
  run_once: true
  when: acme_certificate_verify_auth

- name: DNS sanity checks (2/2)
  ansible.builtin.assert:
    that:
      - "'community.general.cloudflare_dns' is community.general.a_module"
    msg: "The community.general collection must be installed for Cloudflare"
  run_once: true