---
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020, Felix Fontein

argument_specs:
  main:
    short_description: Do account key rollover
    version_added: 0.1.0
    description:
      - This is a role which can use any CA supporting the ACME protocol, such as L(Let's Encrypt,https://letsencrypt.org/),
        L(Buypass,https://www.buypass.com/ssl/products/acme) or L(ZeroSSL,https://zerossl.com/features/acme/), to rekey
        ACME account keys.
      - This role will create a backup copy of the existing account key if requested to do so, re-create the account key,
        and then roll over the ACME account to the new key.
    author:
      - Felix Fontein (@felixfontein)
    options:
      acme_certificate_acme_account:
        type: str
        description:
          - Path to the private ACME account key.
      acme_certificate_acme_account_uri:
        type: str
        description:
          - Instead of determining the account URI from the account key, assumes the given account URI.
      acme_certificate_acme_directory:
        type: str
        default: https://acme-v02.api.letsencrypt.org/directory
        description:
          - The ACME directory to use.
          - Default is C(https://acme-v02.api.letsencrypt.org/directory), which is the current production ACME v2 endpoint of Let's Encrypt.
      acme_certificate_acme_version:
        type: int
        default: 2
        choices:
          - 2
        description:
          - The ACME directory's version.
      acme_certificate_account_algorithm:
        type: str
        default: rsa
        choices:
          - rsa
          - p-256
          - p-384
          - p-521
        description:
          - The algorithm used for creating the account key.
          - The default is C(rsa) for an RSA key.
          - Other choices are C(p-256), C(p-384) or C(p-521) for the NIST elliptic curves C(prime256v1),
            C(secp384r1) and C(secp521r1), respectively.
      acme_certificate_account_key_length:
        type: int
        default: 4096
        description:
          - The bit-size to use for RSA private keys.
          - Should not be less than 2048. Also values above 4096 might not be supported by every ACME CA.
      acme_certificate_account_key_backup:
        type: bool
        default: true
        description:
          - Whether to create a backup of the old account key before rolling over.
      acme_certificate_account_key_sops_encrypted:
        type: bool
        default: false
        description:
          - "Use L(Mozilla sops,https://github.com/mozilla/sops) to encrypt private key. Needs C(.sops.yaml) file
            inside the directory containing the account key or somewhere up the directory chain."
    attributes:
      check_mode:
        description: Can run in C(check_mode) and return changed status prediction without modifying target.
        support: full
      idempotent:
        description:
          - When run twice in a row outside check mode, with the same arguments, the second invocation indicates no change.
          - This assumes that the system controlled/queried by the module has not changed in a relevant way.
        support: none
    examples: |
      ---
      - name: Account key rollover
        hosts: webservers
        vars:
          acme_certificate_acme_directory: https://acme-v02.api.letsencrypt.org/directory
          acme_certificate_acme_version: 2
          # While 4096 is on the paranoid side, note that for something as important
          # as the account key a bit of paranoia does not hurt. (After all, the account
          # key's size does not impact the speed of regular TLS handshakes.)
          key_length: 4096
        roles:
        - role: felixfontein.acme.account_key_rollover
          # We store the key encrypted with SOPS
          acme_certificate_acme_account: 'keys/letsencrypt-account.key.sops'
          acme_certificate_account_key_sops_encrypted: true
