---
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020, Felix Fontein

name: extra-tests
on:
  # Run CI against all pushes (direct commits, also merged PRs) to main, and all Pull Requests
  push:
    branches:
      - main
  pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still testing against latest version of ansible-test for each ansible-base version
  schedule:
    - cron: '0 6 * * *'
env:
  NAMESPACE: felixfontein
  COLLECTION_NAME: acme

jobs:
  extra-sanity:
    name: Extra Sanity
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ansible-core
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Install collection dependencies
        run: >-
          ansible-galaxy collection install -p .
          git+https://github.com/ansible-collections/community.internal_test_tools.git,main
          git+https://github.com/ansible-collections/amazon.aws.git,main
          git+https://github.com/ansible-collections/community.aws.git,main
          git+https://github.com/ansible-collections/community.crypto.git,main
          git+https://github.com/ansible-collections/community.dns.git,main
          git+https://github.com/ansible-collections/community.general.git,main
          git+https://github.com/ansible-collections/community.sops.git,main
          git+https://github.com/ansible-collections/community.library_inventory_filtering.git,stable-1

      - name: Run sanity tests
        run: ../../community/internal_test_tools/tools/run.py --color
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
